"""
Evidentiary Tier Enforcement Module
Ayurvedic Drug Discovery Pipeline

Every output MUST map to one of five evidentiary tiers.
This module is the single source of truth for tier tagging and disclaimer handling.

Reference: AYUSH-64 case study — computational predictions are hypotheses, not clinical proof.
"""

from enum import Enum
from typing import Any, Dict, Optional
from dataclasses import dataclass, field
import datetime
import functools
import logging

logger = logging.getLogger(__name__)

class EvidentiaryTier(str, Enum):
    """
    Five-tier evidence classification mandated by project architecture.
    """
    DATABASE_DERIVED = "DATABASE_DERIVED"  # Tier 1: IMPPAT / curated phytochemical DB
    DOCKING_RESULT = "DOCKING_RESULT"      # Tier 2: AutoDock Vina style docking
    ML_PREDICTION = "ML_PREDICTION"        # Tier 3: Binding-affinity ML model
    XAI_INTERPRETATION = "XAI_INTERPRETATION"  # Tier 4: SHAP / explainable AI
    LITERATURE_EVIDENCE = "LITERATURE_EVIDENCE"  # Tier 5: RAG / LLM-synthesized literature

    @property
    def description(self) -> str:
        return {
            self.DATABASE_DERIVED: "Information directly retrieved from curated phytochemical/traditional-medicine databases (e.g., IMPPAT, PubChem).",
            self.DOCKING_RESULT: "Structure-based computational docking result (e.g., AutoDock Vina). In silico hypothesis, not experimental validation.",
            self.ML_PREDICTION: "Supervised ML model prediction of binding affinity / bioactivity. Correlative, not causal.",
            self.XAI_INTERPRETATION: "Explainable AI interpretation (e.g., SHAP values) of model predictions. Interpretation of a model, not biological ground truth.",
            self.LITERATURE_EVIDENCE: "Scientific literature mined via RAG / synthesized by LLM. Subject to retrieval quality and LLM hallucination risk."
        }[self]

    @property
    def confidence_guidance(self) -> str:
        return {
            self.DATABASE_DERIVED: "High confidence if source DB curated; verify via primary literature.",
            self.DOCKING_RESULT: "Medium-low; requires experimental validation (e.g., SPR, ITC, cellular assay). RMSD <2Å benchmark on PDBbind.",
            self.ML_PREDICTION: "Model-dependent; report RMSE, R², and applicability domain.",
            self.XAI_INTERPRETATION: "Interpret model behavior, not biology; validate with domain expert.",
            self.LITERATURE_EVIDENCE: "Verify citations; LLM may synthesize plausibly but incorrectly."
        }[self]

# Mandatory disclaimer for non-clinical nature of predictions - AYUSH-64 precedent
CLINICAL_DISCLAIMER = (
    "DISCLAIMER: This output is a COMPUTATIONAL PREDICTION generated by an in silico pipeline. "
    "It does NOT constitute clinical proof of efficacy, safety, or therapeutic relevance. "
    "In accordance with AYUSH-64 case study guidelines, any candidate identified (e.g., neuromodulator "
    "hypotheses from anti-epileptic herbs) must be validated through in vitro, in vivo, and clinical studies "
    "under appropriate regulatory oversight (e.g., AYUSH Ministry, CDSCO, FDA). "
    "Do not use for direct clinical decision-making."
)

# Per-tier disclaimers for UI surfacing
TIER_DISCLAIMERS: Dict[EvidentiaryTier, str] = {
    EvidentiaryTier.DATABASE_DERIVED: "Database-derived: sourced from IMPPAT/PubChem curation. Cross-check primary botanical literature.",
    EvidentiaryTier.DOCKING_RESULT: f"{CLINICAL_DISCLAIMER} Docking score (-kcal/mol) is a scoring function estimate, not measured Kd.",
    EvidentiaryTier.ML_PREDICTION: f"{CLINICAL_DISCLAIMER} ML affinity is statistical inference; check applicability domain.",
    EvidentiaryTier.XAI_INTERPRETATION: "XAI interpretation explains model, not underlying biology; may reflect dataset bias.",
    EvidentiaryTier.LITERATURE_EVIDENCE: "Literature/RAG output may contain incomplete retrieval; always verify DOI/PMID."
}

@dataclass
class TieredEvidence:
    """
    Wrapper enforcing tier tagging on every agent output.
    """
    tier: EvidentiaryTier
    data: Any
    source: str
    timestamp: str = field(default_factory=lambda: datetime.datetime.utcnow().isoformat() + "Z")
    disclaimer: str = field(init=False)
    confidence_note: str = field(init=False)
    clinical_proof: bool = field(default=False, init=False)  # Must always remain False for computational
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        self.disclaimer = TIER_DISCLAIMERS[self.tier]
        self.confidence_note = self.tier.confidence_guidance
        # Hard enforcement: no computational tier may claim clinical proof
        if self.tier in {
            EvidentiaryTier.DOCKING_RESULT,
            EvidentiaryTier.ML_PREDICTION,
            EvidentiaryTier.XAI_INTERPRETATION,
            EvidentiaryTier.LITERATURE_EVIDENCE
        }:
            self.clinical_proof = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "evidentiary_tier": self.tier.value,
            "tier_description": self.tier.description,
            "timestamp": self.timestamp,
            "source": self.source,
            "clinical_proof": self.clinical_proof,
            "disclaimer": self.disclaimer,
            "confidence_note": self.confidence_note,
            "data": self.data,
            "metadata": self.metadata
        }

def enforce_tier(tier: EvidentiaryTier, source: str = "unknown"):
    """
    Decorator to enforce tier tagging on agent methods.
    Usage:
        @enforce_tier(EvidentiaryTier.DOCKING_RESULT, source="DockingAgent.run_docking")
        def run_docking(...) -> TieredEvidence: ...
    """
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            result = func(*args, **kwargs)
            # If already TieredEvidence, validate tier matches decorator
            if isinstance(result, TieredEvidence):
                if result.tier != tier:
                    logger.warning(
                        f"Tier mismatch: decorator expects {tier}, but result has {result.tier}. "
                        f"Overriding to decorator tier per policy."
                    )
                    result.tier = tier
                    result.disclaimer = TIER_DISCLAIMERS[tier]
                return result
            # If dict, wrap it
            if isinstance(result, dict):
                # If dict already contains tier enforcement, respect it but wrap
                return TieredEvidence(
                    tier=tier,
                    data=result,
                    source=source,
                    metadata={"wrapped_by": "enforce_tier"}
                )
            # Otherwise wrap raw data
            return TieredEvidence(tier=tier, data=result, source=source)
        return wrapper
    return decorator

def validate_no_clinical_claim(payload: Dict[str, Any]) -> None:
    """
    Safety check: raise if payload claims clinical proof for computational tier.
    Call before returning to frontend.
    """
    forbidden_phrases = [
        "clinically proven",
        "proven effective",
        "clinical efficacy demonstrated",
        "safe for human use based on this result",
        "approved drug based on this docking",
        "confirmed therapeutic"
    ]
    text_blob = str(payload).lower()
    for phrase in forbidden_phrases:
        if phrase in text_blob:
            raise ValueError(
                f"FORBIDDEN CLAIM DETECTED: '{phrase}' present in output flagged as computational. "
                f"Per AYUSH-64 guideline, computational predictions must not be presented as clinical proof. "
                f"Revise to hypothesis language."
            )

# Convenience factory
def make_docking_evidence(data: Any, source: str, **meta) -> TieredEvidence:
    return TieredEvidence(
        tier=EvidentiaryTier.DOCKING_RESULT,
        data=data,
        source=source,
        metadata=meta
    )
